theme: jekyll-theme-cayman
title: Litapp
description: An unofficial Literotica app
show_downloads: true
google_analytics: UA-142185587-1
github:
  zip_url: https://theilluminatus.github.io/litapp/releases/litapp-1.13.apk